Vagrant.configure("2") do |config|
  config.vm.box = "generic/ubuntu2204"
  
  # Define forwarded port correctly
  config.vm.network "forwarded_port", guest: 22, host: 65000

  config.vm.provider "qemu" do |qe|
    qe.arch = "x86_64"
    qe.machine = "q35"
    qe.cpu = "max"
    qe.net_device = "virtio-net-pci"
  end
end

