Vagrant.configure("2") do |config|
  config.vm.box = "perk/ubuntu-2204-arm64"

  config.vm.provider "qemu" do |qe|
    qe.machine = "virt,accel=hvf"  # Use hvf on macOS, or change to "virt,accel=tcg" for software emulation
    qe.cpu = "host"
    qe.memory = "3072"  # Keep it under 4GB
    qe.smp = "2"
    qe.net_device = "virtio-net-device"
    qe.qemuargs = [
      ["-netdev", "user,id=net0,hostfwd=tcp::50022-:22"],
      ["-device", "virtio-net-device,netdev=net0"]
    ]
  end
end

